#!/usr/bin/env bash
set -e
# Wrapper for launching wine programs in the prefix

basedir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source "$basedir/common.sh"
load-env

# only enable steam integration if steam is actually running
if [[ "$enable_steam_integration" == "1" ]] && pgrep steam >/dev/null; then
    if [[ "$use_wine_wow64" == "1" ]]; then
        export LD_PRELOAD="$(readlink -m "$steam_path/ubuntu12_64/gameoverlayrenderer.so")"
    else
        export LD_PRELOAD="$(readlink -m "$steam_path/ubuntu12_32/gameoverlayrenderer.so")"
    fi
    export ENABLE_VK_LAYER_VALVE_steam_overlay_1=1
fi

# disable for now
: <<'EOF'
GAMESCOPE=""
if [[ "$use_gamescope" == "1" ]]; then
    # must set gamescope to be fullscreen or game will not start
    GAMESCOPE="gamescope -f --"
fi
EOF

exec "$basedir/launchwrapper-env" wine "$@"
