#!/usr/bin/env bash
set -e
# Restore some environment variables within the Steam Runtime container

basedir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

if [[ "$use_wine_wow64" = "1" ]]; then
  export PATH="$proton_path/files/bin-wow64/:$PATH"
else
  export PATH="$proton_path/files/bin/:$PATH"
fi

exec "$@"
