#!/usr/bin/env bash
set -e
# Restore some environment variables within the Steam Runtime container

basedir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

if [[ "$faf_use_wow64" = "1" ]]; then
  export PATH="$proton_path/files/bin-wow64/:$PATH"
else
  export PATH="$proton_path/files/bin/:$PATH"
fi

if [[ "$path_append_host_usr" = 1 ]]; then
    export PATH="$PATH:/run/host/usr/bin:/run/host/usr/sbin"
fi

exec "$@"
