#!/bin/bash
# Start the FAF client

basedir="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
cd "$basedir"

source ./common-env
if [[ "$ice_adapter_debug" == "1" ]]; then
    export SHOW_ICE_ADAPTER_DEBUG_WINDOW="true"
fi

export INSTALL4J_JAVA_HOME="$basedir/$java_path"

# libglassgtk3 crashes for some reason, use gtk 2 instead
export JAVA_TOOL_OPTIONS="-Djdk.gtk.version=2"

cd "$dfc_path"
exec ./downlords-faf-client
