#!/bin/bash
# Main setup script
set -e

DXVK_VERSION="1.9.2"
DFC_VERSION="2021.10.0"
PROTON_VERSION="- Experimental"

JAVA_URL="https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz"
JAVAFX_URL="https://gluonhq.com/download/javafx-15-0-1-jmods-linux/"
# winetricks has its own self-updater
WINETRICKS_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"

STEAM_PATH="$HOME/.local/share/Steam"
PROTON_PATH="$STEAM_PATH/steamapps/common/Proton $PROTON_VERSION"
WINE_PATH="$PROTON_PATH/files"
STEAM_GAME_ID="9420"
GAME_PATH="$STEAM_PATH/steamapps/common/Supreme Commander Forged Alliance"
GAME_DATA_PATH="Local Settings/Application Data/Gas Powered Games/Supreme Commander Forged Alliance"

basedir="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
cd "$basedir"

source ./common.sh

if ! jq --version > /dev/null; then
    echo "jq not found. Please install jq."
    exit 1
fi

if ! cabextract --version > /dev/null; then
    echo "cabextract not found. Please install cabextract."
    exit 1
fi

ensure-path "$STEAM_PATH" "Could not find Steam at $STEAM_PATH"
ensure-path "$PROTON_PATH" "Could not find Proton at $PROTON_PATH, please ensure Proton $PROTON_VERSION is installed"
ensure-path "$PROTON_PATH/files" "Proton $PROTON_VERSION does not appear to be extracted. Please run Proton at least once."

# initialize environment file
cat <<EOF > "$basedir/common-env"
# This file is automatically generated by setup.sh and will be overwritten
# when the script is run.

EOF

wineprefix="$basedir/prefix"
write-env "wineprefix" "$wineprefix"
write-env "steam_path" "$STEAM_PATH"
write-env "proton_path" "$PROTON_PATH"
write-env "steam_game_id" "$STEAM_GAME_ID"
write-env "game_path" "$GAME_PATH"
write-env "game_data_path" "$wineprefix/drive_c/users/steamuser/$GAME_DATA_PATH"
write-env "dxvk_hud" "fps,compiler" # sane defaults, probably
write-env "dxvk_config_file" "$basedir/dxvk.conf"
write-env "enable_steam_integration" "1"
write-env "ice_adapter_debug" "1"
write-env "wine_path" "$WINE_PATH"

dxvk_cache_dir="$basedir/dxvk-cache"
mkdir -p "$dxvk_cache_dir"
write-env "dxvk_cache_dir" "$dxvk_cache_dir"

block-print "Downloading winetricks"
wget -O winetricks "$WINETRICKS_URL"
chmod a+x winetricks

"$basedir/update-component.sh" faf-client "$DFC_VERSION"

"$basedir/update-component.sh" java "$JAVA_URL" "$JAVAFX_URL"

block-print "Wineboot"
"$basedir/launchwrapper-env" wine wineboot -u
block-print "Running winetricks"
"$basedir/launchwrapper-env" "$basedir/winetricks" d3dx9 xact
# install dxvk into prefix
"$basedir/update-component.sh" dxvk "$DXVK_VERSION"

# prompt user to log in
echo
echo "Setup complete. Please log in to the FAF client."
echo "Additional configuration needs to be set in order to launch the game properly."
echo "When you are done logging in, please close the client and run './set-client-paths.sh'."
